### ISSUE TITLE
Ошибка при авторизации 

### ISSUE THREAD

**Issue by MazZz3R** [crinny/bars#3]
File "C:\Users\Георгий\AppData\Local\Programs\Python\Python37\lib\site-packages\bars\bars.py", line 35, in _check_for_error
    if request.headers.get('Content-Type') == 'application/json':
AttributeError: 'coroutine' object has no attribute 'headers'

**Comment by crinny** [comment]
> File "C:\Users\Георгий\AppData\Local\Programs\Python\Python37\lib\site-packages\bars\bars.py", line 35, in _check_for_error
> if request.headers.get('Content-Type') == 'application/json':
> AttributeError: 'coroutine' object has no attribute 'headers'

Проблема с последним обновлением httpx. Пока могу лишь перенести библиотеку на requests

**Comment by MazZz3R** [comment]
Можешь перенести, пожалуйста :)

**Comment by crinny** [comment]
> Можешь перенести, пожалуйста :)

Done. Обнови библиотеку

**Comment by MazZz3R** [comment]
спасибо!

**Comment by MazZz3R** [comment]
InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings тоже при авторизации

**Comment by crinny** [comment]
Барс додики и не могут нормально SSL настроить. Предупреждение на работу библиотеки не влияет

**Comment by MazZz3R** [comment]
А, понял :) Насчет барса согласен, странная система какая-то
