### ISSUE TITLE
Api

### ISSUE THREAD

**Issue by MadL0rd** [crinny/bars#4]
Привет, хотел узнать, каким образом ты api прощупал. Мне нужно каким-то образом узнать структуру но не для ученика, а для преподавателя. Если можешь, поделись пожалуйста

**Comment by crinny** [comment]
Использовал Fiddler (на компьютере), HttpCanary (на телефоне), декомпилировал APK приложения и смотрел JS на сайте

**Comment by MadL0rd** [comment]
Да, мне похоже не светит так просто все сделать ибо api в версии преподавателя нет. Спасибо за помощь)
